---
title: "Predictive Analytics For Business with H2O in R"
author: "Mahin Anwar"
date: "12/1/2020"
output:
  pdf_document: default
  html_document: default
---

```{r}
#Import Libraries
library(tidyverse)
library(readxl)
library(h2o)
```

```{r}
#Read Excel Sheets
path <- 'UCI_bank_marketing.xlsx' 
sheets <- excel_sheets(path)
```

```{r}
#Explore Data In Each Sheet
sheets %>%
  map(~ read_excel(path = path, sheet = .)) %>%
  set_names(sheets)
```

```{r}
#Join Data by ID Column (VLOOKUP Equivalent)
data_joined <- sheets[4:7] %>%
  map(~ read_excel(path = path, sheet = .)) %>%
  reduce(left_join)
```

```{r}
#Start H20 Cluster
h2o.init()

```

```{r}
#Data Preperation
data_joined <- data_joined %>%
  mutate_if(is.character, as.factor)

train <- as.h2o(data_joined)

y <- 'TERM_DEPOSIT'
x <- setdiff(names(train), c(y, 'ID'))
```

```{r}
#H2O AutoML Training
aml <- h2o.automl(
  x = x,
  y = y,
  training_frame = train,
  max_runtime_secs = 600,
  balance_classes = TRUE
)
```

```{r}
#View AutoML Leaderboard
lb <- aml@leaderboard 
print(lb, n = nrow(lb))

```

```{r}
#Ensemble Exploration
model_ids <- as.data.frame(aml@leaderboard$model_id)[,1]
se <- h2o.getModel(grep('StackedEnsemble_AllModels', model_ids, value = TRUE)[1])
metalearner <- h2o.getModel(se@model$metalearner$name)
h2o.varimp(metalearner)
h2o.varimp_plot(metalearner)
```

```{r}
#Baselearner Variable Importance

gb <- h2o.getModel(grep('GBM', model_ids, value = TRUE)[1])
h2o.varimp(gb)
h2o.varimp_plot(gb)
```
